# Generated by Django 6.0.7 on 2026-07-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Инструмент')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MusicalPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year_created', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='music.composer', verbose_name='Композитор')),
                ('genre', models.ManyToManyField(blank=True, related_name='pieces', to='music.genre', verbose_name='Жанры')),
                ('instruments', models.ManyToManyField(blank=True, related_name='pieces', to='music.instrument', verbose_name='Инструменты')),
            ],
        ),
    ]
