# Generated by Django 6.0.7 on 2026-07-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'verbose_name': 'Композитор', 'verbose_name_plural': 'Композиторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='musicalpiece',
            options={'verbose_name': 'Музыкальное произведение', 'verbose_name_plural': 'Музыкальные произведения'},
        ),
    ]
