# Generated by Django 6.0.7 on 2026-08-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_composer_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Видео'), ('audio', 'Аудио'), ('sheet', 'Ноты (PDF)'), ('image', 'Изображение нот'), ('link', 'Ссылка')], max_length=20, verbose_name='Тип материала')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='music.musicalpiece', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Материал к произведению',
                'verbose_name_plural': 'Материалы к произведениям',
            },
        ),
    ]
