# Generated by Django 6.0.7 on 2026-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmaterial',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Если выключено — материал видят только педагоги и прикреплённые ученики', verbose_name='Общедоступно'),
        ),
    ]
