# Generated by Django 6.0.7 on 2026-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_musicmaterial_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalpiece',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='pieces_covers/', verbose_name='Обложка'),
        ),
    ]
