# Generated by Django 6.0.7 on 2026-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musicalpiece_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmaterial',
            name='type',
            field=models.CharField(choices=[('video', 'Видео исполнения'), ('audio', 'Аудио'), ('minus', 'Минусовка (инструментал)'), ('plus', 'Плюсовка (с мелодией)'), ('sheet', 'Ноты (PDF)'), ('image', 'Изображение нот'), ('link', 'Ссылка')], max_length=20, verbose_name='Тип материала'),
        ),
    ]
