# Generated by Django 6.0.7 on 2026-07-31 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_studentprofile_teacher'),
        ('music', '0002_alter_composer_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Профиль ученика', 'verbose_name_plural': 'Профили учеников'},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий педагога')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.instrument', verbose_name='Инструмент')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.musicalpiece', verbose_name='Произведение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.studentprofile', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.teacherprofile', verbose_name='Педагог')),
            ],
        ),
    ]
