# Generated by Django 6.0.7 on 2026-08-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20260802_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.teachingassignment', verbose_name='Назначение'),
        ),
    ]
