# Generated by Django 6.0.7 on 2026-08-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_lesson_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
