# Generated by Django 6.0.7 on 2026-08-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_lesson_teacher'),
        ('music', '0002_alter_composer_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='performances/videos/', verbose_name='Видео исполнения')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='education.teachingassignment', verbose_name='Назначение')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='music.musicalpiece', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Исполнение',
                'verbose_name_plural': 'Исполнения',
            },
        ),
        migrations.CreateModel(
            name='PerformanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='education.performance', verbose_name='Исполнение')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.teacherprofile', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Комментарий к исполнению',
                'verbose_name_plural': 'Комментарии к исполнениям',
            },
        ),
    ]
