# Generated by Django 6.0.7 on 2026-08-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_performance_performancecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='teacher',
        ),
    ]
