# Generated by Django 6.0.7 on 2026-08-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_studentprofile_teacher'),
        ('music', '0003_musicmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='performances', to='music.musicmaterial', verbose_name='Материалы исполнения'),
        ),
    ]
