# Generated by Django 6.0.7 on 2026-08-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_lessonmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='education.subject', verbose_name='Предметы'),
        ),
    ]
