# Generated by Django 6.0.7 on 2026-08-22 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'verbose_name': 'Курс (педагог-ученик)', 'verbose_name_plural': 'Курсы (педагог-ученик)'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.teachingassignment', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='education.teachingassignment', verbose_name='Курс'),
        ),
    ]
