# Generated by Django 6.0.7 on 2026-07-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Педагог'), ('student', 'Ученик'), ('parent', 'Родитель')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
