# Generated by Django 6.0.7 on 2026-08-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Получать письма о новых уроках, заданиях и комментариях педагога', verbose_name='Уведомления на почту'),
        ),
    ]
