# Generated by Django 6.0.7 on 2026-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Можно использовать вместо логина при входе', max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
